### ISSUE TITLE
New syntax sketch for bootstrapped compiler

### ISSUE THREAD

**Issue by carpall** [carpall/hx#12]
```rs
const Calculator = type {
  x, y: i64
  r: i64

  pub static const PI = 3.14159
  pub static const from = fn (x, y: i64): Self {
    new { x: x, y: y }
  }

  pub const sum = fn { self.r = self.x + self.y }
  pub const sub = fn { self.r = self.x - self.y }
  pub const mul = fn { self.r = self.x * self.y }
  pub const div = fn { self.r = self.x / self.y as i64 }

  pub const result = fn (): i64 { self.r }
}

const makeFastSum = fn {
  println!("PI: ", Calculator.PI)

  let mut calc = Calculator.from(1, 2)
  calc.sum()
  let result = calc.result()

  println!("Result: ", result)
}

const main = fn {
  static {
    println!("Compile-Time Executed:")
    makeFastSum()
  }

  println!("Runtime Executed:")
  makeFastSum()
}
```

* `const` is for compile time evaluated members
* `let [mut]` is for runtime mutable values

**It's not just a syntax sketch:**
In my opinion it could make the compiler to have a more linear structure, at least in the symbols table, because all symbols are actually `const` or `let [mut]`, there's no other kind of symbol.

**Comment by Carpall** [comment]
```zig
const main = fn {
  const add = fn (a, b: i32): i32 { a + b }

  exit!(add(1, 2))
}
```

**Comment by Carpall** [comment]
```zig
const TokenKind = enum {
  comma,
  BAD, EOF
}
```

**Comment by BartvanLaar** [comment]
Hello,

Might be a bit random, my apologies for that,  but i couldn't find any examples online.
How did you manage to add a custom print function tonyour language? I'm making a toy compiler as well (private repo for now, very early stage) and can't seem to wrap my head around how to create/enable that lind of functionality.

Could you please elaborate/explain or oush me in the right direction for creating a print function in my toy compiler?

Kind Regards,

Bart
